### ISSUE TITLE
README.md中使用说明有误

### ISSUE THREAD

**Issue by Joxon** [wwwpf/QzoneExporter#10]
源代码中第一个参数为self_uin：
https://github.com/wwwpf/QzoneExporter/blob/f9c44481c7babb80fb50fa4d0ffdae20e618f9ab/exporter.py#L885

README.md中第一个参数为uin：
```python
# exporter.py
# 根据需要设定以下变量
target_uin = "需要导出数据的QQ号"
uin = "登录空间的QQ号"
g_tk = "从浏览器获取"
cookies_value = "从浏览器获取"
q = QZoneExporter(uin, g_tk, cookies_value, args, target_uin)
q.export()

print("done")
```

可能是typo？

**Comment by wwwpf** [comment]
感谢指正。
通过上下文能明确 `uin` 的含义，下次一并把它改了。

**Comment by Joxon** [comment]
> 
> 
> 感谢指正。
> 通过上下文能明确 `uin` 的含义，下次一并把它改了。

多谢回复。我在想，如果能够把参数初始化从exporter.py分离出来，单独做一个run.py可能会方便一些。
