### ISSUE TITLE
photo_exif_recover.py脚本报错，json存在exif信息的都有问题。

### ISSUE THREAD

**Issue by gordonyicang** [wwwpf/QzoneExporter#12]
照片是用单反D7000拍的，上传到空间，现在从空间爬下来，重新把exif信息写入图片的时候报错。用手机拍的照片就能写入exif信息成功，应该是单反照片参数过多，photo_exif_recover.py脚本没对多余参数进行处理导致的，望作者有空时能修复一下，万般感激。
![image2f169dd71e0fc3cb.png](https://cdn.wxplay.net/2019/01/26/image2f169dd71e0fc3cb.png)
![image.png](https://cdn.wxplay.net/2019/01/26/image.png)

**Comment by wwwpf** [comment]
可能手机照片中相关参数是空的，所以没有导致 float("0/6") 这种情况 @Yang-z

**Comment by Yang-z** [comment]
嗯，晚上解决。

**Comment by Yang-z** [comment]
Exif中，ExposureBiasValue、ExposureTime、FNumber、FocalLength等参数是以Rational或SRational来存储的。所谓Rational或SRational就是（分子/分母）两个整数。
QZone原本将此类分数转换为单个小数来存储，现在又改为标准的分子/分母来存储，所以脚本未识别。

现已添加支持，测试后上传。
