### ISSUE TITLE
没办法导包是什么原因啊

### ISSUE THREAD

**Issue by bingbingbog** [wwwpf/QzoneExporter#15]
python exporter.py --all
Traceback (most recent call last):
  File "exporter.py", line 9, in <module>
    import requests
ImportError: No module named requests
![image](https://user-images.githubusercontent.com/22880416/57429934-a5775980-7260-11e9-864a-4895b85d3386.png)

**Comment by yuangezhizao** [comment]
`pip3 install requests`
