### ISSUE TITLE
[BUG]无法下载相册图片

### ISSUE THREAD

**Issue by K1two2** [wwwpf/QzoneExporter#18]
![BG7YWL_19-05-24_20-59-58](https://user-images.githubusercontent.com/9145406/58329575-78819400-7e67-11e9-88d8-d9ebf764c3ae.png)

**Comment by K1two2** [comment]
另外脚本是下载的原图吗？

**Comment by K1two2** [comment]
python exporter.py --photo后，to_download.txt数据为空

**Comment by wwwpf** [comment]
会优先使用原图url。
没有导出url的话，有相册的访问权限吗？

**Comment by K1two2** [comment]
相册是所有人都可以访问，QQ号文件夹下的to_download.txt是有数据的，但是每个相册下的to_download.txt是0kb

**Comment by wwwpf** [comment]
几乎所有的 url 都在 photo 文件夹下的 to_download.txt 中，每个相册下的 to_download.txt 只是保存该相册的评论中可能出现的图片 url。
一直出现 Connection aborted 的错误吗？

**Comment by K1two2** [comment]
是的，一直不间断出现 Connection aborted 错误

**Comment by K1two2** [comment]
![BG7YWL_19-05-25_13-45-53](https://user-images.githubusercontent.com/9145406/58365220-7a913480-7ef3-11e9-8bdd-6387b5c68dfe.png)
![BG7YWL_19-05-25_13-46-13](https://user-images.githubusercontent.com/9145406/58365221-7a913480-7ef3-11e9-84b7-5fe6e06ff409.png)

**Comment by K1two2** [comment]
![BG7YWL_19-05-25_13-51-23](https://user-images.githubusercontent.com/9145406/58365267-33577380-7ef4-11e9-8ea0-17bb7995b4de.png)

**Comment by wwwpf** [comment]
这是服务器关闭了连接，试试 photo/to_download.txt 里的 url 能不能在浏览器中访问

**Comment by K1two2** [comment]
用另一个脚本下载成功了
