### ISSUE TITLE
有些说说有多张图片，其实点进去是视频

### ISSUE THREAD

**Issue by jiuqianyuan** [wwwpf/QzoneExporter#19]
说说图片点击进去后直接显示成了大图，无法左右点击查看下一张。未像原QQ空间或者QzoneExporter的相册功能一样弹出一个模态框

并且部分说说看着是图片，点进去其实是视频，QzoneExporter未抓到这些视频

**Comment by wwwpf** [comment]
1，考虑过，太麻烦没写了。
2，没被抓到的视频通过什么方式插入说说的？

**Comment by jiuqianyuan** [comment]
> 1，考虑过，太麻烦没写了。
> 2，没被抓到的视频通过什么方式插入说说的？

2.应该是拿视频首帧作为图片显示在说说上，点击说说的图片不是会弹出模态框显示大图吗，这个时候会播放成对应视频

**Comment by wwwpf** [comment]
应该是服务器返回的数据增加了一个字段，把视频错误地判断成图片了。

**Comment by wwwpf** [comment]
应该是服务器返回的数据增加了一个字段，导致代码错误地把视频判断成图片了。
