### ISSUE TITLE
[BUG]爬图的bug

### ISSUE THREAD

**Issue by chenruisilalala** [wwwpf/QzoneExporter#20]
有些空间相册都没有权限访问，但是说说里面的图是可以访问的，不知道是否是我的操作有问题还是确实存在这个逻辑bug

**Comment by wwwpf** [comment]
整个相册无法访问，但相册中的某些图片放到了说说或者日志中是可能被访问到的，这是QQ空间本身的设计。
这些说说中的图片是无法下载吗？

**Comment by chenruisilalala** [comment]
是的，相册全部关了，但是说说里有图片
[album_info.txt](https://github.com/wwwpf/QzoneExporter/files/3285217/album_info.txt)

**Comment by wwwpf** [comment]
说说有图片是正常的啊，所以 bug 在哪？
