### ISSUE TITLE
为什么用自己的QQ号登陆不能爬取 同一个QQ的记录？

### ISSUE THREAD

**Issue by buerlee** [wwwpf/QzoneExporter#26]
> $ p3 exporter.py --shuoshuo
请输入需要导出数据的QQ号：155++++801
请输入用于登录的QQ号：155++++801
请输入 cookies：***********************
error: **由于对方权限设置，您不能进行此操作**
done

----------------------------------------------------------------

是不是我自己的QQ设置有问题？谢谢。

**Comment by wwwpf** [comment]
有可能串号了，把 cookie 清理一下，重新登录使用新的 cookie。

**Comment by buerlee** [comment]
好，谢谢您的回复。
