### ISSUE TITLE
你好，请问有能获取长说说的办法吗？是不是需要提交别的请求？或者可以稍微改下代码就能实现？

### ISSUE THREAD

**Issue by asdasd1dsadsa** [wwwpf/QzoneExporter#27]
长的说说被截断了，应该就是预览界面的显示量。
技术小白，只知道一点点常识和用轮子，打扰了。

**Comment by wwwpf** [comment]
`has_more_con` 字段标记是否有更多内容，具体请求的 url 可以抓包看一下。
有空会修复长说说内容没有完全获取的问题。

**Comment by asdasd1dsadsa** [comment]
method:POST
url:
https://user.qzone.qq.com/proxy/domain/taotao.qq.com/cgi-bin/emotion_cgi_msgdetail_v6?qzonetoken=<sometoken>&g_tk=<sometk>

body:
tid=<sometid>&uin=<someuin>&t1_source=1&not_trunc_con=1&hostuin=<someuin>&code_version=1&format=fs&qzreferrer=https%3A%2F%2Fuser.qzone.qq.com%2F<someuin>

**Comment by asdasd1dsadsa** [comment]
> `has_more_con` 字段标记是否有更多内容，具体请求的 url 可以抓包看一下。
> 有空会修复长说说内容没有完全获取的问题。

**Comment by asdasd1dsadsa** [comment]
> `has_more_con` 字段标记是否有更多内容，具体请求的 url 可以抓包看一下。
> 有空会修复长说说内容没有完全获取的问题。

python beautiful soap啥的我用不来，我去试试我比较熟的Mathematica了……

**Comment by asdasd1dsadsa** [comment]
method:POST
url:
https://user.qzone.qq.com/proxy/domain/taotao.qq.com/cgi-bin/emotion_cgi_msgdetail_v6?qzonetoken=SomeToken&g_tk=SomeTick

body:
tid=SomeTid&uin=SomeUin&t1_source=1&not_trunc_con=1&hostuin=SomeUin&code_version=1&format=fs&qzreferrer=https%3A%2F%2Fuser.qzone.qq.com%2FSomeUin
