### ISSUE TITLE
有办法获取说说的浏览量么？ 

### ISSUE THREAD

**Issue by binqiangsun** [wwwpf/QzoneExporter#28]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by wwwpf** [comment]
有，在 `https://user.qzone.qq.com/proxy/domain/r.qzone.qq.com/cgi-bin/user/qz_opcnt2` 这个接口里，它返回点赞情况、浏览量 `["newdata"]["PRD"] `等数据，但是请求多了容易被禁，加上这些数据并不那么重要，所以不抓了。

**Comment by wwwpf** [comment]
有，在 `https://user.qzone.qq.com/proxy/domain/r.qzone.qq.com/cgi-bin/user/qz_opcnt2` 这个接口里，它返回点赞情况、浏览量 `["newdata"]["PRD"]` 等数据，但是请求多了容易被禁，加上这些数据并不那么重要，所以不抓了。

**Comment by binqiangsun** [comment]
非常感谢， 解决了我一个大问题
