### ISSUE TITLE
[BUG]【exif信息恢复】当相册没照片或者相册里面有些照片不是jpeg时分别会报不同错误

### ISSUE THREAD

**Issue by CberYellowstone** [wwwpf/QzoneExporter#29]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by wwwpf** [comment]
哪一行报错？

**Comment by CberYellowstone** [comment]
> 哪一行报错？

没有相册的报错是这样的:

开始文件完整性检查
Traceback (most recent call last):
  File ".\photo_exif_recover.py", line 228, in <module>
    photoExifRecoverBatch.batch(False, False)
  File ".\photo_exif_recover.py", line 129, in batch
    for album in album_info["data"]["albumListModeSort"]:
TypeError: 'NoneType' object is not iterable


而有非jpeg文件的报错是这样的:

开始文件完整性检查
***如果照片文件缺失，可单独手工下载，或调高timeout，重新运行exporter.py下载；
***如果相册文件夹缺失，请确认是否有空相册。
按回车开始批处理...
开始批处理
Traceback (most recent call last):
  File ".\photo_exif_recover.py", line 234, in <module>
    photoExifRecoverBatch.batch(should_rename)
  File ".\photo_exif_recover.py", line 197, in batch
    photoExifRecover = PhotoExifRecover(photo_dir, floatview_info, raw_info)
  File ".\photo_exif_recover.py", line 11, in __init__
    self.exif_dict = piexif.load(self.file_dir)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\piexif\_load.py", line 28, in load
    exifReader = _ExifReader(input_data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\piexif\_load.py", line 104, in __init__
    raise InvalidImageDataError("Given file is neither JPEG nor TIFF.")
piexif._exceptions.InvalidImageDataError: Given file is neither JPEG nor TIFF.

就是这样,建议先检查一次有没有相册以及相册内是否全部是jpeg文件

**Comment by wwwpf** [comment]
这是后续的 exif 信息恢复了，爬虫本身没有问题，影响不大。

**Comment by wwwpf** [comment]
@Yang-z

**Comment by Yang-z** [comment]
OK，我回头看下~

**Comment by Yang-z** [comment]
> > 哪一行报错？
> 
> 没有相册的报错是这样的:
> 
> 开始文件完整性检查
> Traceback (most recent call last):
> File ".\photo_exif_recover.py", line 228, in
> photoExifRecoverBatch.batch(False, False)
> File ".\photo_exif_recover.py", line 129, in batch
> for album in album_info["data"]["albumListModeSort"]:
> TypeError: 'NoneType' object is not iterable
> 
 
“没有相册”是指文件目录中有个空的相册文件夹？里面的两个json文件有没有的？

**Comment by CberYellowstone** [comment]
> > > 哪一行报错？
> > 
> > 
> > 没有相册的报错是这样的:
> > 开始文件完整性检查
> > Traceback (most recent call last):
> > File ".\photo_exif_recover.py", line 228, in
> > photoExifRecoverBatch.batch(False, False)
> > File ".\photo_exif_recover.py", line 129, in batch
> > for album in album_info["data"]["albumListModeSort"]:
> > TypeError: 'NoneType' object is not iterable
> 
> “没有相册”是指photo文件目录中有个空的相册文件夹？此空相册文件夹里面的两个json文件有没有的？

有的是在/photo文件夹里面只有album_info.json,有的则是无权限的相册,在/photo/某无权限相册/  文件夹里面有photo_00000-00434.json这种json,这两种情况都会报错

**Comment by Yang-z** [comment]
> 有的是在/photo文件夹里面只有album_info.json

/photo文件夹下只有album_info.json没有相册文件夹？如果这样本就无可处理照片。你log里提示的就是无相册列表["albumListModeSort"]


> 有的则是无权限的相册,在/photo/某无权限相册/ 文件夹里面有photo_00000-00434.json这种json

这种情况是否有对应的floatview_photo_00000-00434.json、有无downloaded文件夹？能否发下log？

这样吧，我先加几个文件（夹）缺失判断好了。




> 建议先检查一次有没有相册以及相册内是否全部是jpeg文件

我做了运行时捕获EXIF写入异常，程序结尾可打印异常清单。非EXIF支持文件格式会触发异常并被俘获处理，不中断程序。



以上修复稍后提交并发起pr
