### ISSUE TITLE
抓取了一个相册非常多的QQ，但是打开相册报错，相册数量较多导致？(之前抓取过另外一个QQ号，相册东西少，没有报错。)

### ISSUE THREAD

**Issue by softshield** [wwwpf/QzoneExporter#31]
KeyError
KeyError: 'id'

Traceback (most recent call last)
This is the Copy/Paste friendly version of the traceback. You can also paste this traceback into a gist: 

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\Desktop\QzoneExporter-master\displayer.py", line 99, in album
    return generator.generate_photo()
  File "C:\Users\admin\Desktop\QzoneExporter-master\generator.py", line 356, in generate_photo
    self._init_album_info()
  File "C:\Users\admin\Desktop\QzoneExporter-master\generator.py", line 453, in _init_album_info
    self._album_info_dict[album["id"]] = album
KeyError: 'id'

**Comment by softshield** [comment]
> 对应的 json 数据里有 id 吗？

album_info.json 这个文件里面id都是有的

**Comment by softshield** [comment]
看了下源码，然后对比了json数据结构：

{
  "code": 0,
  "subcode": 0,
  "message": "",
  "default": 0,
  "data": {
    "albumListModeClass": [
      {
        "albumList": [
          {

似乎和正常的JSON不一样，正常的如下：
{
    "code": 0,
    "subcode": 0,
    "message": "",
    "default": 0,
    "data": {
        "albumListModeSort": [


【albumListModeClass】 和 【albumListModeSort】的区别？

**Comment by wwwpf** [comment]
代码会尝试使用 albumListModeClass 和 albumListModeClass 两个 key 来找数据，把报错的这个json数据删除无关信息后发出来看看？

**Comment by softshield** [comment]
> 代码会尝试使用 albumListModeClass 和 albumListModeClass 两个 key 来找数据，把报错的这个json数据删除无关信息后发出来看看？

{
  "code": 0,
  "subcode": 0,
  "message": "",
  "default": 0,
  "data": {
    "albumListModeClass": [
      {
        "albumList": [
          {
            "allowAccess": 1,
            "anonymity": 2,
            "bitmap": "10000001",
            "classid": 101,
            "comment": 172,
            "createtime": 1262241723,
            "desc": " ",
            "handset": 0,
            "id": "xxx",
            "lastuploadtime": 1550384274,
            "modifytime": 1550383714,
            "name": "xxx",
            "order": 1,
            "pre": "https://b10.photo.store.qq.com/psb?/xxx",
            "priv": 4,
            "pypriv": 4,
            "total": 525,
            "viewtype": 2
          }
        ],
        "classId": 101,
        "nextPageStart": 10,
        "totalInClass": 10,
        "totalInPage": 10
      },
      {
        "albumList": [
          {
            "allowAccess": 1,
            "anonymity": 6,
            "bitmap": "10000001",
            "classid": 104,
            "comment": 3,
            "createtime": 1423483520,
            "desc": " ",
            "handset": 0,
            "id": "xxx",
            "lastuploadtime": 1428591083,
            "modifytime": 1469766202,
            "name": "xxx",
            "order": 0,
            "priv": 4,
            "pypriv": 4,
            "total": 114,
            "viewtype": 6
          }
        ],
        "classId": 104,
        "nextPageStart": 5,
        "totalInClass": 5,
        "totalInPage": 5
      },
      {
        "albumList": [

          {
            "allowAccess": 1,
            "anonymity": 2,
            "bitmap": "10000001",
            "classid": 106,
            "comment": 3,
            "createtime": 1270883484,
            "desc": " ",
            "handset": 0,
            "id": "xxx",
            "lastuploadtime": 1428590647,
            "modifytime": 1428590686,
            "name": "╮xxx",
            "order": 16,
            "priv": 4,
            "pypriv": 3,
            "total": 167,
            "viewtype": 2
          }
        ],
        "classId": 106,
        "nextPageStart": 14,
        "totalInClass": 14,
        "totalInPage": 14
      },
      {
        "albumList": [
          {
            "allowAccess": 1,
            "anonymity": 0,
            "bitmap": "10000000",
            "classid": 107,
            "comment": 0,
            "createtime": 1473161555,
            "desc": "",
            "handset": 1,
            "id": "xxx",
            "lastuploadtime": 1479391921,
            "modifytime": 1479391957,
            "name": "xxx",
            "order": 4294967295,
            "priv": 1,
            "pypriv": 3,
            "total": 0,
            "viewtype": 0
          }
        ],
        "classId": 107,
        "nextPageStart": 0,
        "totalInClass": 1,
        "totalInPage": 1
      }
    ],
    "albumsInUser": 30,
    "classList": [
      {
        "id": 101,
        "name": "人物"
      },
      {
        "id": 100,
        "name": "最爱"
      },
      {
        "id": 102,
        "name": "风景"
      },
      {
        "id": 103,
        "name": "动物"
      },
      {
        "id": 104,
        "name": "游记"
      },
      {
        "id": 105,
        "name": "卡通"
      },
      {
        "id": 106,
        "name": "生活"
      },
      {
        "id": 107,
        "name": "其他"
      }
    ],
    "limit": 0,
    "mode": 3,
    "sortOrder": 2,
    "t": "",
    "user": {
      "diskused": "321.19",
      "microalbum": 0,
      "mspec": 1,
      "ordermode": 1,
      "ordertype": 2,
      "ownerface": 1,
      "preurlspec": "i",
      "time": 1569306326,
      "userbit": 0
    }
  }
}

**Comment by softshield** [comment]
> 代码会尝试使用 albumListModeClass 和 albumListModeClass 两个 key 来找数据，把报错的这个json数据删除无关信息后发出来看看？

{
  "code": 0,
  "subcode": 0,
  "message": "",
  "default": 0,
  "data": {
    "albumListModeClass": [
      {
        "albumList": [
          {
            "allowAccess": 1,
            "anonymity": 2,
            "bitmap": "10000001",
            "classid": 101,
            "comment": 172,
            "createtime": 1262241723,
            "desc": " ",
            "handset": 0,
            "id": "xxx",
            "lastuploadtime": 1550384274,
            "modifytime": 1550383714,
            "name": "xxx",
            "order": 1,
            "pre": "https://b10.photo.store.qq.com/psb?/xxx",
            "priv": 4,
            "pypriv": 4,
            "total": 525,
            "viewtype": 2
          }
        ],
        "classId": 101,
        "nextPageStart": 10,
        "totalInClass": 10,
        "totalInPage": 10
      },
      {
        "albumList": [
          {
            "allowAccess": 1,
            "anonymity": 6,
            "bitmap": "10000001",
            "classid": 104,
            "comment": 3,
            "createtime": 1423483520,
            "desc": " ",
            "handset": 0,
            "id": "xxx",
            "lastuploadtime": 1428591083,
            "modifytime": 1469766202,
            "name": "xxx",
            "order": 0,
            "priv": 4,
            "pypriv": 4,
            "total": 114,
            "viewtype": 6
          }
        ],
        "classId": 104,
        "nextPageStart": 5,
        "totalInClass": 5,
        "totalInPage": 5
      },
      {
        "albumList": [

          {
            "allowAccess": 1,
            "anonymity": 2,
            "bitmap": "10000001",
            "classid": 106,
            "comment": 3,
            "createtime": 1270883484,
            "desc": " ",
            "handset": 0,
            "id": "xxx",
            "lastuploadtime": 1428590647,
            "modifytime": 1428590686,
            "name": "╮xxx",
            "order": 16,
            "priv": 4,
            "pypriv": 3,
            "total": 167,
            "viewtype": 2
          }
        ],
        "classId": 106,
        "nextPageStart": 14,
        "totalInClass": 14,
        "totalInPage": 14
      },
      {
        "albumList": [
          {
            "allowAccess": 1,
            "anonymity": 0,
            "bitmap": "10000000",
            "classid": 107,
            "comment": 0,
            "createtime": 1473161555,
            "desc": "",
            "handset": 1,
            "id": "xxx",
            "lastuploadtime": 1479391921,
            "modifytime": 1479391957,
            "name": "xxx",
            "order": 4294967295,
            "priv": 1,
            "pypriv": 3,
            "total": 0,
            "viewtype": 0
          }
        ],
        "classId": 107,
        "nextPageStart": 0,
        "totalInClass": 1,
        "totalInPage": 1
      }
    ],
    "albumsInUser": 30,
    "classList": [
      {
        "id": 101,
        "name": "人物"
      },
      {
        "id": 100,
        "name": "最爱"
      },
      {
        "id": 102,
        "name": "风景"
      },
      {
        "id": 103,
        "name": "动物"
      },
      {
        "id": 104,
        "name": "游记"
      },
      {
        "id": 105,
        "name": "卡通"
      },
      {
        "id": 106,
        "name": "生活"
      },
      {
        "id": 107,
        "name": "其他"
      }
    ],
    "limit": 0,
    "mode": 3,
    "sortOrder": 2,
    "t": "",
    "user": {
      "diskused": "321.19",
      "microalbum": 0,
      "mspec": 1,
      "ordermode": 1,
      "ordertype": 2,
      "ownerface": 1,
      "preurlspec": "i",
      "time": 1569306326,
      "userbit": 0
    }
  }
}

**Comment by wwwpf** [comment]
这些 json 数据又嵌套了一层，需要再通过 `albumList` 访问，这种数据多吗，这些相册是什么时候创建的？

**Comment by softshield** [comment]
> 这些 json 数据又嵌套了一层，需要再通过 `albumList` 访问，这种数据多吗，这些相册是什么时候创建的？

15年、17年、19年都有

**Comment by Yang-z** [comment]
> 这些 json 数据又嵌套了一层，需要再通过 `albumList` 访问，这种数据多吗，这些相册是什么时候创建的？

看来这种情况photo_exif_recover.py中也要考虑到。

**Comment by wwwpf** [comment]
网页显示时忘记考虑相册在排序视图下的 json 格式

**Comment by wwwpf** [comment]
> > 这些 json 数据又嵌套了一层，需要再通过 `albumList` 访问，这种数据多吗，这些相册是什么时候创建的？
> 
> 看来这种情况photo_exif_recover.py中也要考虑到。

统一一下，调用 `tools.py` 的 `get_album_list_data` 获取数据。

**Comment by Yang-z** [comment]
> > > 这些 json 数据又嵌套了一层，需要再通过 `albumList` 访问，这种数据多吗，这些相册是什么时候创建的？
> > 
> > 
> > 看来这种情况photo_exif_recover.py中也要考虑到。
> 
> 统一一下，调用 `tools.py` 的 `get_album_list_data` 获取数据。

好的，我回头测试一下。
