### ISSUE TITLE
displayer.py--download报错

### ISSUE THREAD

**Issue by wayzlin** [wwwpf/QzoneExporter#38]
导出说说的时候没问题，但是显示数据（输入displayer.py--download）的时候显示：
Traceback (most recent call last):
  File "D:\QzoneExporter-master\displayer.py", line 145, in <module>
    z = ZipFile(os.path.join(
  File "C:\Python38\lib\zipfile.py", line 1216, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'html\\static\\static.zip'
请问要怎么解决？谢谢。

**Comment by wwwpf** [comment]
确认 static.zip 文件是否存在，如果没有可以重新下载放到相应目录。

**Comment by wayzlin** [comment]
我改了一下文件位置不报错了。提示：
 * Serving Flask app "displayer" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 139-672-060
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

但还是没看到网页显示。。

**Comment by wwwpf** [comment]
打开网页输入 <http://127.0.0.1:5000/> 访问

**Comment by wwwpf** [comment]
打开网页访问 <http://127.0.0.1:5000/>

**Comment by wayzlin** [comment]
![QQ截图20191114184524](https://user-images.githubusercontent.com/32737447/68850400-efa92e00-070e-11ea-9a4f-f885a5ae71a2.png)
