### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by oldzhg** [wwwpf/QzoneExporter#42]
成功爬取全部数据后 包括下载图片到本地

使用命令 python3 displayer.py 展示的时候 也的确成功加载 如下图

<img width="1753" alt="截屏2019-11-30上午12 19 39" src="https://user-images.githubusercontent.com/30204608/69881160-1e2a2a00-1307-11ea-8d18-8434678a1d5b.png">

但是并没有出现预期的QQ空间x效果

**Comment by oldzhg** [comment]
另外还想问一个 如果目录下有两个QQ号的文件  该如何调用命令选择使用哪个文件夹下的数据呢

**Comment by oldzhg** [comment]
会了 直接在后面加QQ号就  打扰了。

**Comment by wwwpf** [comment]
> 成功爬取全部数据后 包括下载图片到本地
> 
> 使用命令 python3 displayer.py 展示的时候 也的确成功加载 如下图
> 
> <img alt="截屏2019-11-30上午12 19 39" width="1753" src="https://user-images.githubusercontent.com/30204608/69881160-1e2a2a00-1307-11ea-8d18-8434678a1d5b.png">
> 
> 但是并没有出现预期的QQ空间效果



> 另外还想问一个 如果目录下有两个QQ号的文件 该如何调用命令选择使用哪个文件夹下的数据呢

点击对应头像即可。
