### ISSUE TITLE
[BUG]QQ空间做出调整?

### ISSUE THREAD

**Issue by CberYellowstone** [wwwpf/QzoneExporter#44]
现在的QQ空间抓不到cookie了,
试了好几次了,
main page cui里面没有cookie,
但是有个qzonetoken,
不知道是不是QQ空间做出的调整

**Comment by wwwpf** [comment]
cookie在请求的首部里面啊

**Comment by CberYellowstone** [comment]
> cookie在请求的首部里面啊

![无标题](https://user-images.githubusercontent.com/37031767/71553325-e4a12780-2a48-11ea-917f-0cfb1bee3f03.png)
你看看这个,哪里有啊

**Comment by CberYellowstone** [comment]
> cookie在请求的首部里面啊

github的图不知道你能不能看到,换个图片外链给你
https://yellow-stone.tpddns.cn/blog/wp-content/uploads/2019/12/无标题.png

**Comment by wwwpf** [comment]
你从其他请求里复制cookie也是可以的

**Comment by CberYellowstone** [comment]
> 你从其他请求里复制cookie也是可以的

我从cgi_emotion_list里面找到了cookie,你或许得改一下教程
