### ISSUE TITLE
download.py 111行

### ISSUE THREAD

**Issue by Yang-zzz** [wwwpf/QzoneExporter#7]
--photos 时需改成temp = line.split('\t')，不然部分photo里的文件夹被分成两个，路径错位
--download时，又需改回temp = line.split()，不然下载报错，好像多个url多个回车
（发现也不行，文件下不全，还是会在下载时截断文件夹（文件夹名字中有空格会被截断），我先切回init测试）

具体什么原因，太晚了，看不动了。。。

受greysign启发，写了个exif信息全部写回文件的代码，切回你的最新版测试时发现如上问题。
exif信息写回照片文件的代码可独立运行，不改动你原先代码，回头pull给你。

**Comment by wwwpf** [comment]
已处理相册名称中含有空白字符的情况
